version: '3.1'

services:
  zoo1:
    container_name: single-zookeeper
    image: zookeeper
    restart: always
    hostname: zoo100
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 100
    volumes:
      - ./zoo100/data:/data
      - ./zoo100/datalog:/datalog
